from enum import Enum

class keyboardKeys(Enum):
    a = "a",
    b = "b",
    c = "c",
    d = "d",
    e = "e",
    f = "f",
    g = "g",
    h = "h",
    i = "i",
    j = "j",
    k = "k",
    l = "l",
    m = "m",
    o = "o",
    p = "p",
    q = "q",
    r = "r",
    s = "s",
    t = "t",
    u = "u",
    v = "v",
    w = "w",
    x = "x",
    y = "y",
    z = "z",
    enter = "return",
    backspace = "backspace",
    space = "space",
    arrowLeft = "left",
    arrowRight = "right",
    arrowUp = "up",
    arrowDown = "down"
    